#!/usr/bin/env php

<?php
require 'vendor/autoload.php';

use Makaroni\Database\Migration\UsersTableMigration;

$connection = app()->get('connection');

(new UsersTableMigration($connection))->migrate();
// define other migrations here...